server:
  port: 8088

spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/order_system?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.ly.orderingsystem.entity



